# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpDB1N0l_5fUGN_xP4gi6dE2PKpPghal
"""

# PERSONAL EXPENSE TRACKER

expenses = []


def add_expense():
    print("Add Expense")

    date = input("Enter date (DD-MM-YYYY): ")
    category = input("Enter category: ")
    amount = float(input("Enter amount: "))
    summary = input("Enter summary: ")

    expense = {
        "date": date,
        "category": category,
        "amount": amount,
        "summary": summary
    }

    expenses.append(expense)

    print("Expense added successfully.")


def view_expenses():
    print("All Expenses")

    if len(expenses) == 0:
        print("No expenses found.")
        return

    for i in range(len(expenses)):
        print("Expense", i + 1)
        print("Date:", expenses[i]["date"])
        print("Category:", expenses[i]["category"])
        print("Amount: Rs.", expenses[i]["amount"])
        print("summary:", expenses[i]["summary"])


def total_expense():
    total = 0

    for expense in expenses:
        total = total + expense["amount"]

    print("Total Expense: Rs.", total)


def category_expense():
    print("Category Expense")

    if len(expenses) == 0:
        print("No expenses found.")
        return

    category = input("Enter category: ")
    total = 0

    for expense in expenses:
        if expense["category"].lower() == category.lower():
            total = total + expense["amount"]

    print("Total spent on", category, ": Rs.", total)


def highest_expense():
    if len(expenses) == 0:
        print("No expenses found.")
        return

    highest = expenses[0]

    for expense in expenses:
        if expense["amount"] > highest["amount"]:
            highest = expense

    print("Highest Expense")
    print("Date:", highest["date"])
    print("Category:", highest["category"])
    print("Amount: Rs.", highest["amount"])
    print("summary:", highest["summary"])


def lowest_expense():
    if len(expenses) == 0:
        print("No expenses found.")
        return

    lowest= expenses[0]

    for expense in expenses:
        if expense["amount"] < lowest["amount"]:
            lowest = expense

    print("Lowest Expense")
    print("Date:", lowest["date"])
    print("Category:", lowest["category"])
    print("Amount: Rs.", lowest["amount"])
    print("summary:", lowest["summary"])

def monthly_summary(expenses):
    if len(expenses) == 0:
        print("No expenses in record yet.")
        return

    totals = {}

    for expense in expenses:
        month = expense["date"][3:5]
        year = expense["date"][6:10]
        month_key = month + "-" + year

        if month_key in totals:
            totals[month_key] = totals[month_key] + expense["amount"]
        else:
            totals[month_key] = expense["amount"]

    print("Month-wise totals:")

    for month in totals:
        print(month, ": Rs.", totals[month])

    print()


def main():
    while True:
        print("Personal Expense Tracker")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. View Total Expense")
        print("4. Search by Category")
        print("5. Find Highest Expense")
        print("6. Find Lowest Expense")
        print("7. Monthly Summary")
        print("8. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            add_expense()

        elif choice == "2":
            view_expenses()

        elif choice == "3":
            total_expense()

        elif choice == "4":
            category_expense()

        elif choice == "5":
            highest_expense()

        elif choice == "6":
             lowest_expense()
        elif choice == "7":
            monthly_summary(expenses)
        elif choice == "8":
            print("Thank you for using Personal Expense Tracker.")
            break

        else:
            print("Invalid choice. Please try again.")


main()